export const PLANS = [
  {
    id: "monthly",
    priceId: "price_1Sywb9GiLeHcQYBNBSg0kYRP",
    testPriceId: "price_1SywqWGiLeHcQYBNZXo0GC0K",
    name: "Miesięczny",
    price: "5 zł",
    period: "/ miesiąc",
    perMonth: "5 zł/mies.",
    badge: null,
  },
  {
    id: "semiannual",
    priceId: "price_1SywevGiLeHcQYBNzF2gpcNt",
    testPriceId: "price_1SywuTGiLeHcQYBNjDz7dmbc",
    name: "6 miesięcy",
    price: "25 zł",
    period: "/ 6 miesięcy",
    perMonth: "~4,17 zł/mies.",
    badge: null,
  },
  {
    id: "annual",
    priceId: "price_1SywgIGiLeHcQYBN5Ad1ffwQ",
    testPriceId: "price_1SywuHGiLeHcQYBNZFskrLPn",
    name: "Roczny",
    price: "50 zł",
    period: "/ rok",
    perMonth: "~4,17 zł/mies.",
    badge: "Najlepsza wartość",
  },
] as const;
